### PR TITLE
Start CI build.

### PR DESCRIPTION
**Pull request by monaka**

### CODE REVIEW

**Comment by monaka** [comment]
This PR has been tested on https://github.com/diamondhands-rgb/rgb-lib/pull/2.
I'll mark it as ready after the test is done.

**Comment by monaka** [comment]
CI builds are passed on my repository.
But it is required to merge #3 and #5 before I mark this issue as ready.

**Comment by monaka** [comment]
I checked this patch is fine on my forked repository. Could you review it?

**Comment by nicbus** [comment]
thanks for submitting the PR

LGTM so will now merge and apply some changes on top

**Pull request merged**
